### ISSUE TITLE
Button height problem "Open all unread in tabs"

### ISSUE THREAD

**Issue by gingerbeardman** [lautis/refined-github-safari#14] opened 2020-03-28 19:15 UTC
![Screen shot 2020-03-28 at 16 56 46](https://user-images.githubusercontent.com/49612/77831673-84de1980-7128-11ea-8d00-a89fb97217f2.png)

**Comment by lautis** [comment] 2020-04-10 10:00
I can't reproduce with the latest version. Perhaps fixed in refined-github.

**Closed as completed by lautis** 2020-04-10 10:00 UTC

**Comment by gingerbeardman** [comment] 2020-04-10 10:48
Yes indeed it has been, cheers!
